# molecular conformers formular

* nA = 150-0.2x150+0.1x150 = 135
* nB = 150-0.1x150+0.2x150 = 165

In [2]:
import numpy as np
#part b
def matrixprob(vector):
    p = np.array([[0.8,1.2],
                  [1.1,0.9]])
    
    mult = vector * p
    print("p: ",p)
    print("mult: ", mult)
    #todo test hermitian matrix

vector = np.array([[150],
                   [150]])   
matrixprob(vector)

p:  [[0.8 1.2]
 [1.1 0.9]]
mult:  [[120. 180.]
 [165. 135.]]


In [3]:
#part c

def transition(conformerA, conformerB):
    newB = 20*conformerA/100
    newA = 10*conformerB/100 - newB
    
    newB = newB - 10*conformerB/100
    
    B1 = newB+ conformerB
    A1 = newA + conformerA
    print("conformerA", A1)
    print("ConformerB", B1)
    
    vector = np.array([[A1],
                       [B1]])
    print(vector)
    return vector

#set up loop for 72 hours

def longtime(vector):
    conformerA = vector[0][0]
    conformerB = vector[1][0]
    vector = transition(conformerA, conformerB)
    print("newA and B: ", vector)
    return vector


for x in range(0,72):
    vector = longtime(vector)

conformerA 135.0
ConformerB 165.0
[[135.]
 [165.]]
newA and B:  [[135.]
 [165.]]
conformerA 124.5
ConformerB 175.5
[[124.5]
 [175.5]]
newA and B:  [[124.5]
 [175.5]]
conformerA 117.15
ConformerB 182.85
[[117.15]
 [182.85]]
newA and B:  [[117.15]
 [182.85]]
conformerA 112.00500000000001
ConformerB 187.995
[[112.005]
 [187.995]]
newA and B:  [[112.005]
 [187.995]]
conformerA 108.40350000000001
ConformerB 191.5965
[[108.4035]
 [191.5965]]
newA and B:  [[108.4035]
 [191.5965]]
conformerA 105.88245
ConformerB 194.11755
[[105.88245]
 [194.11755]]
newA and B:  [[105.88245]
 [194.11755]]
conformerA 104.117715
ConformerB 195.882285
[[104.117715]
 [195.882285]]
newA and B:  [[104.117715]
 [195.882285]]
conformerA 102.8824005
ConformerB 197.11759949999998
[[102.8824005]
 [197.1175995]]
newA and B:  [[102.8824005]
 [197.1175995]]
conformerA 102.01768035
ConformerB 197.98231965
[[102.01768035]
 [197.98231965]]
newA and B:  [[102.01768035]
 [197.98231965]]
conformerA 101.412376245
ConformerB 198.587